import React from 'react';
import {
  SiExpress,
  SiJavascript,
  SiNodedotjs,
  SiJsonwebtokens,
  SiTypescript,
  SiMongodb,
  SiPostgresql,
  SiJest,
  SiFirebase,
  SiNextdotjs,
  SiHeroku,
  SiVercel,
  SiRedux,
  SiReact,
  SiCss3,
  SiHtml5,
  SiTailwindcss,
  SiBabel,
  SiWebpack,
  SiGraphql,
  SiTestinglibrary,
  SiGit,
  SiJira,
  SiAuth0,
  SiSlack,
  SiConfluence,
} from 'react-icons/si';

export const technologyMap = new Map([
  ['javascript', <SiJavascript key="javascript" size={50} color="#F0DB4F" />],
  ['nodejs', <SiNodedotjs key="nodejs" size={50} color="#3c873a" />],
  ['express', <SiExpress key="express" size={50} />],
  [
    'jsonwebtokens',
    <SiJsonwebtokens key="jsonwebtokens" size={50} color="#00e0c6" />,
  ],
  ['react', <SiReact key="react" size={50} color="#61DBFB" />],
  ['typescript', <SiTypescript key="typescript" size={50} color="#007acc" />],
  ['mongodb', <SiMongodb key="mongodb" size={50} color="#0cd45b" />],
  ['jest', <SiJest key="jest" size={50} color="#C63D14" />],
  ['firebase', <SiFirebase key="firebase" size={50} color="#FFCB2B" />],
  ['next.js', <SiNextdotjs key="nextjs" size={50} />],
  ['heroku', <SiHeroku key="heroku" size={50} color="#6762A6" />],
  ['vercel', <SiVercel key="vercel" size={50} color="#00e0c6" />],
  ['redux', <SiRedux key="redux" size={50} color="#764abc" />],
  ['postgresql', <SiPostgresql key="sql" size={50} />],
  ['CSS', <SiCss3 key="css3" size={50} color="#2965f1" />],
  ['HTML', <SiHtml5 key="html5" size={50} color="#e34c26  " />],
  [
    'Tailwind CSS',
    <SiTailwindcss key="tailwindcss" size={50} color="#37BCF8" />,
  ],
  ['Babel', <SiBabel key="babel" size={50} color="#F0DB4F" />],
  ['Webpack', <SiWebpack key="webpack" size={50} />],
  ['GraphQL', <SiGraphql key="graphql" size={50} color="#e535ab" />],
  [
    'Testing Library',
    <SiTestinglibrary key="testinglibrary" size={50} color="#C63D14" />,
  ],
  ['Git', <SiGit key="git" size={50} color="#F1502F" />],
  ['Jira', <SiJira key="jira" size={50} color="#0052CC" />],
  ['Slack', <SiSlack key="slack" size={50} />],
  ['Confluence', <SiConfluence key="confluence" size={50} color="#0052CC" />],
  ['Auth0', <SiAuth0 key="auth0" size={50} color="#eb5424" />],
]);
